### ISSUE TITLE
Bottom sheet is expanding behind bottom navigation bar

### ISSUE THREAD

**Issue by mddanishansari** [composablehorizons/composables-core#19]
My screen is inside `Scaffold` and I have used both Modal bottom sheet and standard bottom sheet from `composables-core`.

Modal bottom sheet works fine but standard bottom sheet is expanding behind the bottom navigation bar. Is there ay workaround for this?

![1726647752291](https://github.com/user-attachments/assets/aabe7e40-2eb2-4d9c-8628-cc1d065e8c65)

**Comment by mddanishansari** [comment]
Also the standard bottom sheet also works fine if I use it outside the `Scaffold` and as a sibling to `Scaffold`

**Comment by alexstyl** [comment]
Im happy to help but keep in mind that your question is about Material Compose rather than the sheets in Composables Core.

Scaffold doesn't seem to have a slot for bottom sheets. If I were you I would wrap your scaffold and the bottom sheet into a `Box()` so that the bottom sheet is placed above the scaffold.

**Comment by mddanishansari** [comment]
Alright got it thanks
