### ISSUE TITLE
Add support for [Preview] bottom sheet

### ISSUE THREAD

**Issue by mak1nt0sh** [composablehorizons/composables-core#6]
Currently there's no way to pass `ModalBottomSheetState` directly to preview composable. Should not require passing the `rememberModalBottomSheetState`.

```
public class ModalBottomSheetState internal constructor(
    internal val bottomSheetDetent: SheetDetent,
    internal val sheetDetents: List<SheetDetent>,
    internal val animationSpec: AnimationSpec<Float>
)
```

It is internal.

**Comment by alexstyl** [comment]
> Should not require passing the rememberModalBottomSheetState

why do you believe that?

**Comment by mak1nt0sh** [comment]
Oh, I see that the previews will work with remember. Coming from Material3 BottomSheets, the remember block doesn't let setting sheet state as expanded for preview. I guess we can close the issue, however I haven't still tried the library due to #5

**Comment by alexstyl** [comment]
Just had a go and preview for `ModalBottomSheet` does work.

However the `ModalBottomSheet` is always animated into the screen no matter the `initialDetent` you pass. 

Because of this you can only preview the sheet while in Interactive Mode, so that it "enters" the screen.

<img width="1728" alt="Screenshot 2024-08-01 at 14 09 23" src="https://github.com/user-attachments/assets/6a1e9825-ce32-4f06-9695-65941da7f62f">
